In [24]:
## 1

###array : 연속적으로 할당되고 같은 데이터 타입의 데이터를 저장할 수 있는 자료구조(배열)

## 기본적으로 생성하는 방법

import numpy as np
arr = np.array([1,2,3,4])

## python에서 built-in type
## int, float, bool, str, list, tuple, dict, set
## =>이 data type이라고 알고 있던 것들이 실제로는 class로 되어있다.
## 그리고 type()이라는 함수로 class를 확인할 수 있다.
print(type(arr))
print(arr)
## 차원의 수 파악
print(arr.ndim)
## 차원 및 요소의 수 파악
print(arr.shape)

## 2차원 이상의 ndarray를 만들려면 어떻게 해야하나요?
myList =[[1,2,3],[4,5,6]]
arr = np.array(myList)
print(arr)

## 전체요소개수 파악
print(arr.size)

## len in NumPy 1차원의 개수를 알려줌
print(len(arr)) 
print(arr.shape)


myList =[[1,2,3],[4,5,6]]
arr = np.array(myList, dtype= np.float64)
print(arr)

### 다양한 생성방법
### np.zeros(), np.ones(), np.full(), np.empty()
### np.arange(), np.linspace()
### random기반의 함수들 -> 4가지 rand, randn, random, randint

<class 'numpy.ndarray'>
[1 2 3 4]
1
(4,)
[[1 2 3]
 [4 5 6]]
6
2
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]


In [66]:
## NumPy활용에 대해서 알아보자
## shape을 조절해서 내가 원하는 형태의 ndarray를 만들어 보자
import numpy as np
arr = np.arange(0,12,1)
print(arr)

## 2차원으로 변경
## reshape을 이용하면 view가 만들어짐 => 원본 데이터가 변환되는 것이 아님 => 실제데이터는 arr이 가짐
arr1 = arr.reshape(4,3) # 4행 3열
print(arr1)

## view는 base속성이 있다. 원본데이터를 알려줌
print(arr1.base is arr) # True 출력
print(arr1.base == arr) # 요소  각각의 값을 비교
print(arr1.base) # [ 0  1  2  3  4  5  6  7  8  9 10 11] 출력

## shape을 변경해서 새로운 ndarray를 만들고 싶어 1차원 => n차원
arr = np.arange(0,12,1)
print(arr)

arr1 = arr.reshape(4,3).copy() #새로운 ndarray를 생성

# arr1 = arr.reshape(5,3) # 사이즈 안 맞추면 에러난다.
arr1 = arr.reshape(-1,4) # -1집어넣으면 남은 행,열 알아서 계산 처리 해준다

arr = np.arange(0,100,1).reshape(10,-1).copy()
print(arr)

#다차원 배열을 1차원으로 만들수 있어요 n차원 => 1차원
arr1 = np.ravel(arr)
print(arr1)

#2 >ravel> 1 >reshape> 3 의 과정으로 차원 변경

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
True
[ True  True  True  True  True  True  True  True  True  True  True  True]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [77]:
## resize()는 reshape()과 유사
## reshape()은 형태가 맞지 않으면 변경시 에러발생
## 하지만 resize()는 가능!
arr = np.arange(0,10,1)
print(arr)

## resize()방식의 2가지 방법
## 1.원본은 두고 return 받는 방식
arr1 = np.resize(arr,(2,6)) #변경된 ndarray를 return
print(arr1)                 #모자라는 부분은 배여르이 처음부터 다시 추가

arr2 = np.resize(arr,(2,2)) #남는요소는 버리고 채운다.
print(arr2)

## 2.원본을 바꾸고 그 결과값을 사용
arr = np.arange(0,10,1)
result = arr.resize(2,3) #원본의 값을 바꾼다!
print(arr)



[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
[[0 1]
 [2 3]]
[[0 1 2]
 [3 4 5]]


In [109]:
## NumPy array를 가로 혹은 세로방향으로 붙여보자
## 2행 3열짜리 ndarray를 생성

## 정수로 생성, 랜덤하게 균등분포로 0~10사이에서 추출
## 6개를 추출해서 2차원 ndarray로 생성
np.random.seed(1) #난수값 고정
arr1 = np.random.randint(0,10,(2,3))
print(arr1)

## 1. 가로방향으로 붙여보자(행의 개수 확인)
arr2 = np.random.randint(0,10,(2,5))
print(arr2)

np.hstack((arr2,arr1)) #tuple 형태로 묶어서 작성

## 1. 세로방향으로 붙여보자(열의 개수 확인)
arr1 = np.random.randint(0,10,(2,5))
arr2 = np.random.randint(0,10,(2,5))
np.vstack((arr1,arr2))

##################################### ndarray의 생성 및 특징 #######################################
########################### reshape(), resize() => view(효율적 메모리사용을 위해)  ##################
############################### 여러개의 ndarray를 결합할 수 있다. ##################################
############################## 이제 indexing과 slicing에 대해 알아보자 ##############################


[[5 8 9]
 [5 0 0]]
[[1 7 6 9 2]
 [4 5 2 4 2]]


array([[4, 7, 7, 9, 1],
       [7, 0, 6, 9, 9],
       [7, 6, 9, 1, 0],
       [1, 8, 8, 3, 9]])

In [131]:
## NumPy array의 Indexing 과 slicing

'''arr = np.arange(10,20,1)
print(arr)'''

#data만 추출해서 사용하는 for
'''for i in arr:  
    print("data : {}".format(i))

#index까지 추출하는 enumerate()
for (idx,data) in enumerate(arr):
    print("index : {}, data : {}".format(idx,data))'''
    
arr = np.arange(0,5,1)
print(arr)
print(arr[2])   #indexing
print(arr[1:3]) #slicing [1 2]
print(arr[:])
print(arr[1::2])# [1 3] 출력 idx1부터 끝까지 2칸띄고 출력
print(arr[-1:]) # [4] 출력
print(arr[-1])  # 4 출력

[0 1 2 3 4]
2
[1 2]
[0 1 2 3 4]
[1 3]
[4]
4


In [155]:
######################## indexing은 값으로 나옴, slicing은 영역으로 나옴!!!##########################
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
# print(arr[1,2])   #indexing
# print(arr[:,0])   # [0 4 8] 출력 
# print(arr[:,0:1]) # 결과 값이 다름!!

# [5 6 9 10] 출력?
print(arr[1:3,1:3].ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 5  6  9 10]


In [164]:
## Boolean Indexing & Fancy Indexing
## boolean indexing은 mask를 이용해서 배열의 각 요소의 선택여부를
## True, False로 지정해서 True요소만 선택하는 방식

## 정수형 난수를 추출해 보아요!
np.random.seed(1)
arr = np.random.randint(0,10,(10,))
print(arr)

##여기에서 짝수만 추출
'''result = list()
for i in arr:
    if i % 2 == 0:
        result.append(i)
result = np.array(result)
print(result)'''

## 로직보다 간단한 방법을 쓰자
## 1. 조건에 맞는 mask를 만들자
## arr = [5 8 9 5 0 0 1 7 6 9]
## mask : [False  True False False  True  True False False  True False]
print(arr % 2 == 0)
print(arr[arr % 2 == 0])

[5 8 9 5 0 0 1 7 6 9]
[False  True False False  True  True False False  True False]
[8 0 0 6]


In [204]:
## Fancy indexing : 비 연속적인 구간을 들고 오고 싶을때
## indexing을 할 때 배열을 이용해서 배열요소를 찾는 방식

arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)

# print(arr[2,2])
# print(arr[1:2,2])

# print(arr[[0,2],])  # 원하는 행만 추출
# print(arr[[0,2],2]) # 원하는 행에서 2열만 추출
# print(arr[[0,2],1:])

# print(arr[:,[0,2]])
print()
print(arr[[1,2],[1,2]]) #  [ 5 10] 출력?? 조심해야함
                       #   둘다 Faccy indexing으로 뽑아내면 안됨
print()
# 방법 1
print(arr[[1,2],][:,[1,2]])

print()
# 방법 2 np.ix_() :둘다 Faccy indexing으로 뽑아내게 해주는 함수
print(arr[np.ix_([1,2],[1,2])])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 5 10]

[[ 5  6]
 [ 9 10]]

[[ 5  6]
 [ 9 10]]


In [219]:
## ndarray의 연산
## R의 vector연산과 유사
np.random.seed(1)
arr1 = np.arange(1,7,1).reshape(2,3).copy()
arr2 = np.random.randint(1,10,(2,3))
print(arr1)
print()
print(arr2)
print()
print(arr1 + arr2) #python의 list에서 + 연산하면 list가 늘어남
print()            #numpy ndarray에서 + 연산은 vector 연산
print(arr1 + 10 )  #원래는 연산이 안돼야 정상 why? 사이즈가 달라
print()            #이렇게 타입이 안맞는 경우에는 scalar를 broadcasting시킨다(행과 열을 확장시킴)
                   #10 => 2행 3열짜리 10으로 모두 채워진 ndarray로 변환
arr2 = np.array([1,2,3])
print(arr1 + arr2)
print()


[[1 2 3]
 [4 5 6]]

[[6 9 6]
 [1 1 2]]

[[ 7 11  9]
 [ 5  6  8]]

[[11 12 13]
 [14 15 16]]

[[2 4 6]
 [5 7 9]]



In [232]:
## 기본적인 집계(통계)함수
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
print()

#합
print(np.sum(arr))
print(arr.sum())
print()

#누적 (1차원으로 변환)
print(np.cumsum(arr))
print()

#평균
print(np.mean(arr))
print()

#최대 최솟갑
print(np.max(arr))
print(np.min(arr))
print()

#std
print(np.std(arr))
print()

#제곱근
print(np.sqrt(arr))
print()

#자연로그, 상용로그
print(np.log10(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

66
66

[ 0  1  3  6 10 15 21 28 36 45 55 66]

5.5

11
0

3.452052529534663

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]

[[      -inf 0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125 0.84509804]
 [0.90308999 0.95424251 1.         1.04139269]]


C:\Users\student\Anaconda3\envs\cpu_env\lib\site-packages\ipykernel_launcher.py:32: RuntimeWarning: divide by zero encountered in log10


In [260]:
## 축 개념을 이해해 보아요
## 위에 있는 집계함수를 이용할 때 axis 개념을 사용
## 만약 axis를 명시하지 않으면 axis를 None으로 설정하고 대상범위를 전체 ndarray로 지정

# 1차원 ndarray
arr = np.arange(0,5,1)
print(arr)
print(arr.sum()) #축을 명시하지 않은 경우
print(arr.sum(axis=0)) # 1차원에서 axis=0 이면 열방향
print()

# 2차원
arr = np.arange(12).reshape(3,4).copy()
print(arr)
print()
print(arr.sum(axis=0)) # 2차원에서 axis=0 이면 행방향
print(arr.sum(axis=1)) # 2차원에서 axis=1 이면 열방향

# 3차원일땐?
# 3차원에서 axis=0 이면 면방향
# 3차원에서 axis=1 이면 행방향
# 3차원에서 axis=2 이면 행방향

## 일반적인 로직으로 프로그램을 하는 것보다 집계함수를 이용하는 것이 훨씬 효율적


[0 1 2 3 4]
10
10

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[12 15 18 21]
[ 6 22 38]


In [267]:
##연습
np.random.seed(1)
arr = np.random.randint(1,10,(2,5))
print(arr)

print(len(arr[arr > 5]))
(arr>5).sum()
arr[arr > 5].size

[[6 9 6 1 1]
 [2 8 7 3 5]]
5


5

In [281]:
## delete() : axis를 기준으로 행과 열을 삭제
## axis을 지정하지 않으면 1차배열로 변환한 후 해당 요소를 삭제
## 원본은 유지하고 삭제된 복사본을 return


arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
print()
# axis를 지정하지 않고 삭제 처리
'''result = np.delete(arr,(1,4)) # 1차배열로 변환한 후 해당 인덱스를 삭제
print(result)'''

result = np.delete(arr,1,axis=0) # [1,]행을 삭제
print(result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 8  9 10 11]]
